## defaults for _all_ profiles
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19" # to use a specific local solc install set the path as `solc = "<path to solc>/solc"`
eth-rpc-url = "https://rpc.ankr.com/eth"
remappings = ["@forge-std/=lib/forge-std/src/", "@gelato/=lib/ops/contracts/", "@openzeppelin/=lib/openzeppelin-contracts/"]

## set only when the `hardhat` profile is selected
[profile.hardhat]
src = "contracts"
out = "artifacts"
libs = ["node_modules"]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}", url = "${GOERLI_RPC_URL}" }
mumbai = { key = "${POLYGON_ETHERSCAN_API_KEY}", url = "${MUMBAI_RPC_URL}" }